/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moonsolid.sc;

public class App {
  public static void main(String[] args) {
    System.out.println("오늘도 안녕하세요!");
  

    }
}
